### ISSUE TITLE
Cannot pip install docker-run-cli on remote

### ISSUE THREAD

**Issue by mechgguy** [ika-rwth-aachen/acdc-research-projects#8]
I cannot install docker-run-cli on remote rhea5 server. 
It Throws this error while running this command: ```pip install docker-run-cli ``` 
```shell
error: could not create '/home/manas/.local/lib/python3.8/site-packages/GPUtil': No space left on device
``` 
I need docker-run to run acdc notebooks and ros1_run.sh from docker file of acdc.

**Comment by lreiher** [comment]
Please try again, there should be sufficient disk space at the moment. I'll have another look at the available disk space on Monday.

Also, please post issues to our GitLab server instead of public ones on GitHub.
